# Generated by Django 5.0.6 on 2024-06-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('Dependents', models.IntegerField(default=0)),
                ('ApplicantIncome', models.IntegerField(default=0)),
                ('CoapplicantIncome', models.IntegerField(default=0)),
                ('LoanAmount', models.IntegerField(default=0)),
                ('Credit_History', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('Married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('Education', models.CharField(choices=[('Graduate', 'Graduate'), ('Not_Graduate', 'Not_Graduate')], max_length=15)),
                ('Self_Employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('Area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
