# Generated by Django 5.0.6 on 2024-06-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankloan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='Education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('NonGraduate', 'NonGraduate')], max_length=15),
        ),
    ]
