# Generated by Django 5.0.6 on 2024-06-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankloan_app', '0002_alter_approvals_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='Area',
            new_name='Property_Area',
        ),
    ]
